spring.application.name=CarSalApp

spring.datasource.url=jdbc:oracle:thin:@//localhost:1521/XEPDB1
spring.datasource.username=salon_admin
spring.datasource.password=Pswd
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
