spring.application.name=CarSalApp

spring.datasource.url=jdbc:oracle:thin:@//localhost:1521/XEPDB1
spring.datasource.username=salon_admin
spring.datasource.password=Pswd
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect

logging.level.org.springframework.security=DEBUG
logging.level.org.hibernate.SQL=DEBUG

spring.thymeleaf.cache=false

spring.security.user.name=admin
spring.security.user.password=admin123
spring.security.user.roles=ADMIN
