ALTER SESSION SET CONTAINER = XEPDB1;

BEGIN
    EXECUTE IMMEDIATE 'DROP USER salon_admin CASCADE';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -1918 THEN
            RAISE;
        END IF;
END;
/

CREATE USER salon_admin IDENTIFIED BY salon123
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  QUOTA UNLIMITED ON USERS;

GRANT CONNECT, RESOURCE TO salon_admin;
GRANT CREATE SESSION TO salon_admin;
GRANT CREATE TABLE TO salon_admin;
GRANT CREATE SEQUENCE TO salon_admin;
GRANT CREATE TRIGGER TO salon_admin;
GRANT CREATE PROCEDURE TO salon_admin;
GRANT CREATE VIEW TO salon_admin;
GRANT CREATE SYNONYM TO salon_admin;

SELECT username, account_status, default_tablespace 
FROM dba_users 
WHERE username = 'SALON_ADMIN';

EXIT;
